---
title: "credit_card_unbalanced"
author: "Ziyuan(Esther) Yan"
date: "3/8/2020"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytext)
library(keras)
library(radiant)
```

# Credit card: Create a balanced sample

```{r}
credit_card <- read_rds("../data/credit_card.rds")
```

```{r}
credit_card <- credit_card %>%
  mutate(important = (ifelse(`Company response to consumer` == "Closed with monetary relief", 1, 0)))

table(credit_card$important)
```

```{r}
maxWords <- 8000 # only use the top 8000 words
tokenizer <- text_tokenizer(num_words = maxWords) %>%
  fit_text_tokenizer(credit_card$`Consumer complaint narrative`)

sequences <- texts_to_sequences(tokenizer, credit_card$`Consumer complaint narrative`)

word_index <- tokenizer$word_index

nReviews <- nrow(credit_card)
nReviews
```

```{r}
## one-hot code tokens and reshuffle data
x <- sequences_to_matrix(tokenizer, sequences, mode = c("binary"))
y <- as.numeric(credit_card$important)
```

```{r}
credit_card <- credit_card %>%
  mutate(wordCount = sapply(strsplit(`Consumer complaint narrative`, " "), length),
         std_wordCount = standardize(wordCount))
```

```{r}
x <- cbind(x, credit_card$std_wordCount)
```

```{r}
set.seed(1234)
shuffIndex <- sample(1:nReviews)
nTrain <- floor(nReviews * 0.7)

trainIndex <- shuffIndex[1:nTrain]
testIndex <- shuffIndex[(nTrain + 1):nReviews]

xTrain <- x[trainIndex, ]
yTrain <- y[trainIndex]

xTest <- x[testIndex, ]
yTest <- y[testIndex]
```

```{r}
model <- keras_model_sequential() %>%
  layer_dense(units = 256, activation = "relu", input_shape = ncol(x)) %>%
  layer_dense(units = 256, activation = "relu") %>%
  layer_dense(units = 256, activation = "relu") %>%
  layer_dense(units = 1, activation = "sigmoid")
model
```

```{r}
model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("AUC")
)
```

```{r}
historyT <- model %>% fit(
  xTrain,
  yTrain,
  epochs = 20,
  batch_size = 256,
  validation_split = 0.3
)
```

```{r}
## re-train at optimized epoch
theEpoch <- which.min(historyT$metrics$val_loss)

model <- keras_model_sequential() %>%
  layer_dense(units = 256, activation = "relu", input_shape = ncol(x)) %>%
  layer_dense(units = 256, activation = "relu") %>%
  layer_dense(units = 256, activation = "relu") %>%
  layer_dense(units = 1, activation = "sigmoid")

model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("AUC")
)

history <- model %>% fit(xTrain, yTrain, epochs = theEpoch, batch_size = 256)

## @knitr predictModel

results <- model %>% evaluate(xTest, yTest)
results
```

```{r}
prediction <- model %>% predict(xTest)

xTest_credit_card_org <- credit_card[testIndex,]
xTest_credit_card_org <- cbind(xTest_credit_card_org, prediction) %>%
  select(`Consumer complaint narrative`, `Company response to consumer`, important, prediction) %>%
  arrange(desc(prediction)) %>%
  mutate(Monetary = ifelse(prediction > 0.5, 1, 0))

conf_matrix <- table(xTest_credit_card_org$important, xTest_credit_card_org$Monetary)
accuracy <- (conf_matrix[1, 1] + conf_matrix[2, 2])/sum(conf_matrix)
accuracy

reacall <- conf_matrix[2,2]/(conf_matrix[2,2]+conf_matrix[2,1])
reacall


a <- xTest_credit_card_org %>%
  slice(1:20)

a
```

```{r}
theTestIndices <- c(8225, 6350)
theTestIndices
```

```{r}
cat(str_wrap(credit_card$`Consumer complaint narrative`[testIndex[theTestIndices[1]]], width = 60))
```

```{r}
cat(str_wrap(credit_card$`Consumer complaint narrative`[testIndex[theTestIndices[2]]], width = 60))
```

```{r}
cat(str_wrap(credit_card$`Consumer complaint narrative`[testIndex[theTestIndices[3]]], width = 60))
```

```{r}
model %>% predict(xTest[theTestIndices, ])
```
